package secure

// Wire-spec conformance: docs/interop-vectors.json is the golden vector file
// generated by TestGenerateWireSpecVectors (source of truth:
// docs/WIRE_SPEC.md). This test CONSUMES the committed file the way any
// independent implementation would, so a regression in the format or the
// crypto breaks here first.

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/liqdmetal/spore/internal/crypto"
	"github.com/liqdmetal/spore/internal/whisper"
)

type vectors struct {
	FixedScalars struct {
		AliceX25519Priv string `json:"alice_x25519_priv"`
		BobX25519Priv   string `json:"bob_x25519_priv"`
		EphX25519Priv   string `json:"eph_x25519_priv"`
		Nonce24         string `json:"nonce_24"`
	} `json:"fixed_scalars"`
	DerivedKeys struct {
		AliceX25519Pub string `json:"alice_x25519_pub"`
		BobX25519Pub   string `json:"bob_x25519_pub"`
		EphX25519Pub   string `json:"eph_x25519_pub"`
		AliceSigPub    string `json:"alice_sig_pub"`
		AeadKey        string `json:"aead_key"`
	} `json:"derived_keys"`
	Canonical struct {
		EncodeTextInput     string `json:"encode_text_input"`
		EncodeTextHex       string `json:"encode_text_hex"`
		EncodePointerEphPub string `json:"encode_pointer_eph_pub"`
		EncodePointerBodyCid string `json:"encode_pointer_body_cid"`
		EncodePointerHex    string `json:"encode_pointer_hex"`
	} `json:"canonical"`
	EnvelopeV2Text struct {
		RecipientX25519Pub string `json:"recipient_x25519_pub"`
		SenderX25519Priv   string `json:"sender_x25519_priv"`
		EphX25519Priv      string `json:"eph_x25519_priv"`
		Nonce              string `json:"nonce"`
		InnerCanonicalHex  string `json:"inner_canonical_hex"`
		CiphertextHex      string `json:"ciphertext_hex"`
		ExpectedPayloadHex string `json:"expected_payload_hex"`
	} `json:"envelope_v2_text"`
	EnvelopeV2Pointer struct {
		ExpectedPayloadHex string `json:"expected_payload_hex"`
	} `json:"envelope_v2_pointer"`
	SporePeerFrame struct {
		BodyHex           string `json:"body_hex"`
		ExpectedOkFrame   string `json:"expected_ok_frame"`
		ExpectedErrText   string `json:"expected_err_text"`
		ExpectedErrFrame  string `json:"expected_err_frame"`
	} `json:"spore_peer_frame"`
}

func loadVectors(t *testing.T) vectors {
	t.Helper()
	raw, err := os.ReadFile("../../docs/interop-vectors.json")
	if err != nil {
		t.Fatalf("vectors file missing (run TestGenerateWireSpecVectors): %v", err)
	}
	var v vectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("bad vectors JSON: %v", err)
	}
	return v
}

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(strings.TrimSpace(s))
	if err != nil {
		t.Fatalf("bad hex %q: %v", s, err)
	}
	return b
}

func TestSpecCanonicalVectors(t *testing.T) {
	v := loadVectors(t)
	// Text: encode matches, decode round-trips.
	got := whisper.EncodeTextCanonical(v.Canonical.EncodeTextInput)
	if !bytes.Equal(got, mustHex(t, v.Canonical.EncodeTextHex)) {
		t.Fatalf("canonical text mismatch:\n got %x\nwant %s", got, v.Canonical.EncodeTextHex)
	}
	kind, text, _, _, ok := whisper.DecodeCanonical(got)
	if !ok || kind != whisper.KindText || text != v.Canonical.EncodeTextInput {
		t.Fatalf("canonical text decode failed: kind=%d text=%q ok=%v", kind, text, ok)
	}
	// Pointer: encode matches, decode round-trips.
	ptr := whisper.EncodePointerCanonical(mustArr32(t, v.Canonical.EncodePointerEphPub), mustArr32(t, v.Canonical.EncodePointerBodyCid))
	if !bytes.Equal(ptr, mustHex(t, v.Canonical.EncodePointerHex)) {
		t.Fatalf("canonical pointer mismatch:\n got %x\nwant %s", ptr, v.Canonical.EncodePointerHex)
	}
	kind, _, eph, cid, ok := whisper.DecodeCanonical(ptr)
	if !ok || kind != whisper.KindPointer || eph != mustArr32(t, v.Canonical.EncodePointerEphPub) || cid != mustArr32(t, v.Canonical.EncodePointerBodyCid) {
		t.Fatalf("canonical pointer decode failed: kind=%d ok=%v", kind, ok)
	}
}

func TestSpecEnvelopeV2Vector(t *testing.T) {
	v := loadVectors(t)
	inner := mustHex(t, v.EnvelopeV2Text.InnerCanonicalHex)
	eph := mustHex(t, v.FixedScalars.EphX25519Priv)
	nonce := mustHex(t, v.FixedScalars.Nonce24)
	sender := mustHex(t, v.EnvelopeV2Text.SenderX25519Priv)
	recipient := mustHex(t, v.EnvelopeV2Text.RecipientX25519Pub)

	// Deterministic construction must reproduce the committed payload byte for
	// byte — this is the interop contract.
	got, err := EncryptDeterministic(eph, nonce, sender, recipient, inner)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, mustHex(t, v.EnvelopeV2Text.ExpectedPayloadHex)) {
		t.Fatalf("envelope v2 mismatch:\n got %x\nwant %s", got, v.EnvelopeV2Text.ExpectedPayloadHex)
	}

	// Stage-by-stage verification an independent implementer can follow:
	//   secret = X25519(eph_priv, recipient_pub)
	secret, err := crypto.SharedSecret(eph, recipient)
	if err != nil {
		t.Fatal(err)
	}
	//   key = HKDF-SHA256(secret, info="spore/e2e/v1/key" || eph_pub || recipient_pub)
	ephPub, err := PubKeyOf(eph)
	if err != nil {
		t.Fatal(err)
	}
	key, err := crypto.DeriveKeyBound(secret, ephPub, recipient)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(key, mustHex(t, v.DerivedKeys.AeadKey)) {
		t.Fatalf("HKDF-bound key mismatch:\n got %x\nwant %s", key, v.DerivedKeys.AeadKey)
	}
	//   ciphertext = XChaCha20-Poly1305(key, nonce, inner)
	if !bytes.Equal(cryptoSealForSpec(t, inner, key, nonce), mustHex(t, v.EnvelopeV2Text.CiphertextHex)) {
		t.Fatal("ciphertext stage mismatch")
	}
	//   sigPub = Ed25519(seed = SHA256("spore/sig/v1/seed" || sender_priv))
	sigPub, err := SigPubOf(sender)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(sigPub, mustHex(t, v.DerivedKeys.AliceSigPub)) {
		t.Fatalf("sig pubkey mismatch:\n got %x\nwant %s", sigPub, v.DerivedKeys.AliceSigPub)
	}

	// Receiver side: Open must verify the signature, decrypt, and attribute.
	plain, gotSigPub, err := Open(mustHex(t, v.FixedScalars.BobX25519Priv), got)
	if err != nil {
		t.Fatalf("Open failed: %v", err)
	}
	if !bytes.Equal(plain, inner) {
		t.Fatal("Open plaintext mismatch")
	}
	if !bytes.Equal(gotSigPub, sigPub) {
		t.Fatal("Open did not attribute to the sender's sig key")
	}
}

func TestSpecPointerEnvelopeVector(t *testing.T) {
	v := loadVectors(t)
	// Build the pointer canonical, seal it deterministically, compare with the
	// committed pointer-envelope vector.
	ptr := whisper.EncodePointerCanonical(mustArr32(t, v.Canonical.EncodePointerEphPub), mustArr32(t, v.Canonical.EncodePointerBodyCid))
	got, err := EncryptDeterministic(
		mustHex(t, v.FixedScalars.EphX25519Priv),
		mustHex(t, v.FixedScalars.Nonce24),
		mustHex(t, v.EnvelopeV2Text.SenderX25519Priv),
		mustHex(t, v.EnvelopeV2Text.RecipientX25519Pub),
		ptr,
	)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, mustHex(t, v.EnvelopeV2Pointer.ExpectedPayloadHex)) {
		t.Fatalf("pointer envelope mismatch:\n got %x\nwant %s", got, v.EnvelopeV2Pointer.ExpectedPayloadHex)
	}
	plain, _, err := Open(mustHex(t, v.FixedScalars.BobX25519Priv), got)
	if err != nil {
		t.Fatal(err)
	}
	_, _, eph, cid, ok := whisper.DecodeCanonical(plain)
	if !ok || eph != mustArr32(t, v.Canonical.EncodePointerEphPub) || cid != mustArr32(t, v.Canonical.EncodePointerBodyCid) {
		t.Fatal("pointer envelope did not decrypt to the canonical pointer")
	}
}

// TestSpecSporePeerFrame: Go-side conformance for the spore-peer transport
// frame — the same bytes the Rust implementation must produce. Frame =
// LE32(len) + payload; ok payload = 0x00 + body; err payload = 0x01 + ascii.
// The body starts with ASCII '4' on purpose (audit H4: the first byte must
// never decide anything; the status byte and the hash do).
func TestSpecSporePeerFrame(t *testing.T) {
	v := loadVectors(t)
	body := mustHex(t, v.SporePeerFrame.BodyHex)

	// Build the ok frame independently and compare.
	okPayload := append([]byte{0x00}, body...)
	okFrame := append(le32(uint32(len(okPayload))), okPayload...)
	if hex.EncodeToString(okFrame) != strings.ToLower(v.SporePeerFrame.ExpectedOkFrame) {
		t.Fatalf("ok frame mismatch:\n got %x\nwant %s", okFrame, v.SporePeerFrame.ExpectedOkFrame)
	}

	// Parse the ok frame: status 0x00, body intact, sha256 == its own CID.
	if okFrame[4] != 0x00 {
		t.Fatal("ok frame missing status byte 0x00")
	}
	gotBody := okFrame[5:]
	if !bytes.Equal(gotBody, body) {
		t.Fatal("ok frame body mismatch")
	}
	cid := sha256.Sum256(gotBody)
	_ = cid // integrity gate: sha256(body) must equal the requested CID

	// Parse the err frame: status 0x01 + the exact error text.
	errFrame := mustHex(t, v.SporePeerFrame.ExpectedErrFrame)
	if errFrame[4] != 0x01 {
		t.Fatal("err frame missing status byte 0x01")
	}
	if !bytes.Equal(errFrame[5:], []byte(v.SporePeerFrame.ExpectedErrText)) {
		t.Fatalf("err frame text = %q, want %q", errFrame[5:], v.SporePeerFrame.ExpectedErrText)
	}
}

// --- helpers ---

func mustArr32(t *testing.T, hexStr string) [32]byte {
	t.Helper()
	b := mustHex(t, hexStr)
	if len(b) != 32 {
		t.Fatalf("expected 32 bytes, got %d", len(b))
	}
	var out [32]byte
	copy(out[:], b)
	return out
}

func le32(n uint32) []byte {
	var b [4]byte
	binary.LittleEndian.PutUint32(b[:], n)
	return b[:]
}

func cryptoSealForSpec(t *testing.T, plaintext, key, nonce []byte) []byte {
	t.Helper()
	ct, err := crypto.Seal(plaintext, key, nonce)
	if err != nil {
		t.Fatal(err)
	}
	return ct
}
