package main

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/liqdmetal/spore/internal/backend"
	"github.com/liqdmetal/spore/internal/chain"
	"github.com/liqdmetal/spore/internal/maildb"
	"github.com/liqdmetal/spore/internal/nostr"
	"github.com/liqdmetal/spore/internal/notify"
	"github.com/liqdmetal/spore/internal/ratchet"
	"github.com/liqdmetal/spore/internal/ratchetwire"
	"github.com/liqdmetal/spore/internal/store"
)

// msgE2 is deliberately separate from legacy msg: it has no one-shot
// fallback and never accepts plaintext as a command-line flag (argv is
// visible to shell history, `ps`, and crash/monitoring reports). Bundles can
// be supplied explicitly (-bundle) or fetched from a mailbox's /prekey
// endpoint (-bundle-url); either way, EstablishInitiator still verifies the
// bundle's SPK_sig against -pinned-sig, so discovery is a transport
// convenience only and never substitutes for out-of-band trust.
func msgE2(args []string) {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "usage: spore msg send-e2|recv-e2 [flags]")
		return
	}
	switch args[0] {
	case "send-e2":
		msgSendE2(args[1:])
	case "recv-e2":
		msgRecvE2(args[1:])
	case "reply-e2":
		msgReplyE2(args[1:])
	case "forward-e2":
		msgForwardE2(args[1:])
	case "sessions":
		msgSessions(args[1:])
	case "prekeygen":
		msgPrekeygen(args[1:])
	case "compose":
		msgCompose(args[1:])
	case "flush":
		msgFlush(args[1:])
	case "mail":
		msgMail(args[1:])
	case "invoice":
		msgInvoiceE2(args[1:])
	case "pay":
		msgPayE2(args[1:])
	default:
		fmt.Fprintln(os.Stderr, "msg: unknown e2 subcommand")
	}
}

// e2Store builds the off-chain body store from a -store URL. Two schemes:
//
//	http(s)://host    -> HTTPStore (your mailbox, or a paid Model-B operator)
//	nostr://r1,r2,r3  -> NostrStore: bodies live on a public relay commons
//
// The nostr:// form is the NO-SERVERS endgame: nobody operates a store for
// you, and any subset of the relays can serve a body by content address.
//
// nostr:// needs a signing key, and it must be a DEDICATED one — publishing
// bodies is linkable by pubkey, so reusing the ratchet identity or a chain key
// would let a relay tie storage activity to messaging identity. -store-key
// (a 32-byte hex file, generated by `spore init`) supplies it; it is required
// for the nostr scheme and ignored for http.
func e2Store(url, token, keyFile string) (ratchetwire.BodyStore, error) {
	if url == "" {
		return nil, errors.New("-store is required (E2 never uses a local-only implicit store)")
	}
	if rest, ok := strings.CutPrefix(url, "nostr://"); ok {
		var relays []string
		for _, r := range strings.Split(rest, ",") {
			if r = strings.TrimSpace(r); r != "" {
				if !strings.HasPrefix(r, "wss://") && !strings.HasPrefix(r, "ws://") {
					r = "wss://" + r
				}
				relays = append(relays, r)
			}
		}
		if len(relays) == 0 {
			return nil, errors.New("-store nostr:// requires at least one relay (e.g. -store nostr://relay.damus.io,nos.lol)")
		}
		if keyFile == "" {
			return nil, errors.New("-store nostr:// requires -store-key (a DEDICATED body-store signing key file; `spore init` writes one at store.key — do not reuse your identity or chain key, publishing is linkable by pubkey)")
		}
		k, err := readHexFile(keyFile, 32)
		if err != nil {
			return nil, err
		}
		// Index next to the key so Delete/Reap survive restarts. Without it
		// we could still Get, but Reap would have nothing to iterate — i.e.
		// bodies would never be cleaned up from the commons.
		indexPath := ""
		if dir := filepath.Dir(keyFile); dir != "" && dir != "." {
			indexPath = filepath.Join(dir, "nostrstore-index.json")
		}
		return nostr.NewNostrStore(nostr.NostrStoreConfig{
			PrivateKey: hex.EncodeToString(k),
			Relays:     relays,
			IndexPath:  indexPath,
		})
	}
	return store.NewHTTPStoreWithToken(url, token)
}
func e2Carrier(fs *flag.FlagSet) (ratchetwire.ChainCarrier, error) {
	value := func(name string) string {
		if f := fs.Lookup(name); f != nil {
			return f.Value.String()
		}
		return ""
	}
	privateKey := value("private-key")
	if path := value("private-key-file"); path != "" {
		b, err := os.ReadFile(path)
		if err != nil {
			return ratchetwire.ChainCarrier{}, err
		}
		privateKey = strings.TrimSpace(string(b))
	}
	var relays []string
	if raw := value("relays"); raw != "" {
		for _, r := range strings.Split(raw, ",") {
			if r = strings.TrimSpace(r); r != "" {
				relays = append(relays, r)
			}
		}
	}
	cfg := backend.ChainConfig{Type: value("chain"), RPC: value("rpc"), Login: value("rpc-login"), From: value("from"), KeyFile: value("keyfile"), ProgramID: value("program"), PrivateKey: privateKey, Network: value("network"), BaseURL: value("base-url"), Address: value("address"), Name: value("chain-id"), PostPath: value("post-path"), ListPath: value("list-path"), HeightPath: value("height-path"), MessageField: value("message-field"), RecipientField: value("recipient-field"), DeliveryGuaranteed: value("delivery-guaranteed") == "true", Relays: relays}
	c, err := backend.Build(context.Background(), cfg)
	if err != nil {
		return ratchetwire.ChainCarrier{}, err
	}
	var codec ratchetwire.ChainPayloadCodec
	switch strings.ToLower(c.Name()) {
	case "dero":
		codec = ratchetwire.DeroChainCodec{}
	case "evm", "solana":
		codec = ratchetwire.JSONCodec{}
	case "nostr", "bitcoin", "cosmos", "ton":
		codec = ratchetwire.CanonicalChainCodec{}
	default:
		return ratchetwire.ChainCarrier{}, fmt.Errorf("E2 pointer carrier unsupported on %s; refusing downgrade", c.Name())
	}
	return ratchetwire.ChainCarrier{Chain: c, Codec: codec}, nil
}
func readHexFile(path string, n int) ([]byte, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	x, err := hex.DecodeString(strings.TrimSpace(string(b)))
	if err != nil || (n > 0 && len(x) != n) {
		return nil, fmt.Errorf("%s must contain %d-byte hex", path, n)
	}
	return x, nil
}
func readBundle(path string) (*ratchet.SPKBundle, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var out ratchet.SPKBundle
	if err := json.Unmarshal(b, &out); err != nil {
		return nil, wrongBundleFileError(path, b, err)
	}
	if err := validateBundleStruct(&out); err != nil {
		// A structurally-empty bundle is almost always the wrong FILE (an
		// identity card, a batch, or unrelated JSON), so diagnose the file
		// rather than only reporting the zero fields.
		return nil, wrongBundleFileError(path, b, err)
	}
	return &out, nil
}

// validateBundleStruct is the shared structural gate for a decoded SPKBundle,
// used by BOTH the file (-bundle) and discovery (-bundle-url) paths.
//
// json.Unmarshal ignores unknown fields, so `{}` or `{"bundle":{}}` parses
// cleanly into an all-zero SPKBundle. Without this check a zero bundle would
// reach the X3DH handshake and fail later as a confusing signature error
// instead of "you pointed at the wrong file".
func validateBundleStruct(b *ratchet.SPKBundle) error {
	if b == nil {
		return errors.New("nil bundle")
	}
	if b.IKPub == [32]byte{} || b.SPKPub == [32]byte{} || b.SPKSig == [64]byte{} {
		return errors.New("bundle has no identity/signed-prekey material (all-zero fields)")
	}
	// OPKPub nil with a nonzero OPKID is inconsistent: degraded mode must
	// carry OPKID 0. Mirrors the mailbox's own bundle validation.
	if b.OPKPub != nil {
		if *b.OPKPub == [32]byte{} {
			return errors.New("bundle declares an OPK id but the OPK public key is zero")
		}
	} else if b.OPKID != 0 {
		return fmt.Errorf("bundle declares OPK id %d with no OPK public key", b.OPKID)
	}
	return nil
}

// wrongBundleFileError diagnoses the common ways -bundle gets handed the wrong
// file, naming the mistake and the fix rather than surfacing a raw Go type
// error that tells the user nothing.
func wrongBundleFileError(path string, b []byte, cause error) error {
	var probe struct {
		IKPub   string            `json:"ik_pub"`
		Bundles []json.RawMessage `json:"bundles"`
	}
	if json.Unmarshal(b, &probe) == nil {
		if len(probe.Bundles) > 0 {
			return fmt.Errorf("%s is a prekey BATCH (push it with `spore prekeybatch push`); -bundle wants a single SPKBundle, or use -bundle-url to fetch one from the recipient's mailbox", path)
		}
		if probe.IKPub != "" {
			return fmt.Errorf("%s is an identity CARD (ik_pub + pinned_sig), not a prekey bundle; -bundle wants a single SPKBundle. Share the card so your contact can pin you, and fetch THEIR bundle with -bundle-url http://THEIR-MAILBOX/prekey", path)
		}
	}
	return fmt.Errorf("%s is not a valid SPKBundle: %w", path, cause)
}

// fetchBundle discovers a recipient's public prekey bundle from a mailbox's
// GET /prekey endpoint. This is a transport convenience over -bundle FILE.json
// only: EstablishInitiator still verifies SPK_sig against the caller-supplied
// -pinned-sig, so a compromised or malicious mailbox can at worst withhold or
// serve a stale bundle (causing send-e2 to fail) — it cannot forge a bundle
// that passes signature pinning, and it never sees plaintext, ciphertext, or
// any private key material (this is a GET with no body).
func fetchBundle(ctx context.Context, url, token string) (*ratchet.SPKBundle, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}
	resp, err := (&http.Client{Timeout: 15 * time.Second}).Do(req)
	if err != nil {
		return nil, fmt.Errorf("bundle discovery: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusNotFound {
		return nil, errors.New("bundle discovery: recipient has not published a prekey bundle")
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("bundle discovery: unexpected status %s", resp.Status)
	}
	var wire struct {
		Bundle ratchet.SPKBundle `json:"bundle"`
	}
	dec := json.NewDecoder(io.LimitReader(resp.Body, 16<<10))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&wire); err != nil {
		return nil, fmt.Errorf("bundle discovery: malformed response: %w", err)
	}
	// Same structural gate as readBundle: a mailbox returning {"bundle":{}}
	// (or a partial bundle) must not reach the X3DH handshake as a zero value.
	if err := validateBundleStruct(&wire.Bundle); err != nil {
		return nil, fmt.Errorf("bundle discovery from %s: %w", url, err)
	}
	return &wire.Bundle, nil
}

// readPlaintext resolves the message body without ever putting it on the
// command line: shell history, `ps`/process listings, and crash/monitoring
// tools all read argv. -msg-file reads a file (use /dev/stdin or a named
// pipe for scripting); with neither flag set, plaintext is read from stdin
// so it never appears as a process argument.
func readPlaintext(msgFile string) ([]byte, error) {
	if msgFile != "" {
		if msgFile == "-" {
			return readAllTrimNewline(os.Stdin)
		}
		b, err := os.ReadFile(msgFile)
		if err != nil {
			return nil, err
		}
		return trimTrailingNewline(b), nil
	}
	return readAllTrimNewline(os.Stdin)
}

func readAllTrimNewline(r io.Reader) ([]byte, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}
	return trimTrailingNewline(b), nil
}

func trimTrailingNewline(b []byte) []byte {
	b = bytes.TrimSuffix(b, []byte("\n"))
	b = bytes.TrimSuffix(b, []byte("\r"))
	return b
}

func e2Common(fs *flag.FlagSet) {
	fs.String("config", "", "config file path (default ~/.spore/config.json or $SPORE_CONFIG)")
	fs.String("chain", "dero", "pointer carrier: dero|evm|solana|nostr|bitcoin|cosmos|ton (xmr unsupported)")
	fs.String("rpc", "", "chain RPC")
	fs.String("rpc-login", "", "RPC user:pass")
	fs.String("from", "", "sender chain address")
	fs.String("keyfile", "", "Solana signer JSON")
	fs.String("program", "", "Solana program ID")
	fs.String("private-key", "", "Nostr private key (prefer -private-key-file)")
	fs.String("private-key-file", "", "file containing Nostr private key")
	fs.String("relays", "", "comma-separated Nostr relay URLs")
	fs.String("network", "", "carrier network")
	fs.String("base-url", "", "carrier API base URL")
	fs.String("address", "", "carrier wallet/address")
	fs.String("chain-id", "", "Cosmos chain ID")
	fs.String("post-path", "", "carrier post path")
	fs.String("list-path", "", "carrier list path")
	fs.String("height-path", "", "carrier height path")
	fs.String("message-field", "", "Cosmos message field")
	fs.String("recipient-field", "", "Cosmos recipient field")
	fs.Bool("delivery-guaranteed", false, "assert carrier preserves exact pointer delivery")
	fs.String("store", "", "HTTP off-chain frame store URL (http(s)://mailbox) OR nostr://relay1,relay2 for the serverless commons")
	fs.String("store-token", "", "bearer token for an HTTP store (ignored for nostr://)")
	fs.String("store-key", "", "file with a 32-byte hex DEDICATED signing key for -store nostr:// (do NOT reuse identity/chain keys — publishing is linkable by pubkey; `spore init` writes one)")
	fs.String("state-dir", "", "encrypted endpoint session state directory (required)")
	fs.String("state-key", "", "file containing 32-byte hex state encryption key (required)")
	fs.Duration("session-ttl", 0, "inactivity TTL for durable E2 sessions (zero disables expiry)")
	// Name resolution: -to accepts a nickname from the address book (which
	// also supplies that contact's pinned sig) or a DeroNS name via -daemon.
	fs.String("maildb", "", "local mail store (maildb JSON): supplies -to nickname -> address + pinned-sig, and indexes received messages")
	fs.String("daemon", "", "DERO daemon RPC for DeroNS name resolution of -to (address only; pinned sig still needed out-of-band)")
}

func msgPrekeygen(args []string) {
	fs := flag.NewFlagSet("msg prekeygen", flag.ExitOnError)
	identity := fs.String("identity-out", "", "identity private key hex output (0600)")
	spk := fs.String("spk-out", "", "signed-prekey private key hex output (0600)")
	opk := fs.String("opk-out", "", "optional one-time-prekey private key hex output (0600)")
	bundle := fs.String("bundle-out", "", "public SPKBundle JSON output (0644)")
	spkID := fs.Uint("spk-id", 1, "signed-prekey identifier")
	opkID := fs.Uint("opk-id", 1, "one-time-prekey identifier")
	_ = fs.Parse(args)
	if err := loadConfigForFlags(fs); err != nil {
		check(err)
	}
	if *identity == "" || *spk == "" || *bundle == "" {
		check(errors.New("prekeygen requires -identity-out -spk-out -bundle-out"))
	}
	key := func() []byte {
		b := make([]byte, 32)
		if _, e := rand.Read(b); e != nil {
			check(e)
		}
		return b
	}
	ik, sk := key(), key()
	var op *[32]byte
	if *opk != "" {
		x := key()
		op = &[32]byte{}
		copy(op[:], x)
	}
	b, err := ratchet.BuildBundle(ik, sk, uint32(*spkID), op, uint32(*opkID))
	check(err)
	write := func(path string, data []byte, mode os.FileMode) {
		if err := os.WriteFile(path, data, mode); err != nil {
			check(err)
		}
		if err := os.Chmod(path, mode); err != nil {
			check(err)
		}
	}
	write(*identity, []byte(hex.EncodeToString(ik)+"\\n"), 0600)
	write(*spk, []byte(hex.EncodeToString(sk)+"\\n"), 0600)
	if *opk != "" {
		write(*opk, []byte(hex.EncodeToString(op[:])+"\\n"), 0600)
	}
	data, err := json.MarshalIndent(b, "", "  ")
	check(err)
	write(*bundle, append(data, '\n'), 0644)
}

func msgSendE2(args []string) {
	fs := flag.NewFlagSet("msg send-e2", flag.ExitOnError)
	to := fs.String("to", "", "recipient chain address")
	identity := fs.String("identity", "", "file containing sender identity private key hex")
	bundle := fs.String("bundle", "", "recipient SPK bundle JSON file (mutually exclusive with -bundle-url)")
	bundleURL := fs.String("bundle-url", "", "fetch recipient SPK bundle from a mailbox GET /prekey URL (mutually exclusive with -bundle; discovery is a transport convenience only — -pinned-sig is still required and still verified)")
	bundleToken := fs.String("bundle-token", "", "bearer token for -bundle-url, if the mailbox requires auth")
	pinned := fs.String("pinned-sig", "", "recipient signing public key hex")
	amount := fs.String("amount", "", "pay-with-message: value to attach to the SAME tx as the pointer, in whole units with asset suffix (e.g. 5.5dero, 0.0001evm). DERO + EVM-calldata only today; the money and the message are atomic — both land or neither does")
	msgFile := fs.String("msg-file", "", "file containing plaintext (use '-' or omit for stdin; never pass plaintext as an argv flag — argv is visible to shell history, ps, and crash reports)")
	ttl := fs.Duration("ttl", 24*time.Hour, "frame retention")
	e2Common(fs)
	_ = fs.Parse(args)
	if err := loadConfigForFlags(fs); err != nil {
		check(err)
	}
	// -pinned-sig is NOT required up front: a maildb contact nickname supplies
	// it (see resolveTo in sendE2Core). Requiring it here would defeat the
	// whole point of the address book.
	if *to == "" || *identity == "" {
		check(errors.New("send-e2 requires -to (address, contact nickname, or DeroNS name) and -identity; bundle comes from -bundle, -bundle-url, or a contact added with `spore msg mail add -invite`; plaintext via -msg-file or stdin"))
	}
	if *bundle != "" && *bundleURL != "" {
		check(errors.New("send-e2: -bundle and -bundle-url are mutually exclusive (omit both to use a contact's invite)"))
	}
	if err := sendE2Core(fs, *to, *identity, *bundle, *bundleURL, *bundleToken, *pinned, *msgFile, *amount, *ttl); err != nil {
		check(err)
	}
}

// sendE2Core is the shared send path for send-e2 and the offline-compose
// flush. fs must be a parsed e2Common FlagSet. Errors are returned (caller
// decides fatal vs spool-retry) and the plaintext never touches argv.
// amount is the optional pay-with-message value ("5.5dero"); empty = postage
// only.
func sendE2Core(fs *flag.FlagSet, to, identity, bundle, bundleURL, bundleToken, pinned, msgFile, amount string, ttl time.Duration) error {
	// Name resolution: -to accepts a raw address, a maildb contact NICKNAME
	// (which also supplies that contact's pinned sig, so -pinned-sig can be
	// omitted), or a DeroNS name via -daemon. Resolved here so every send
	// path (send-e2, forward-e2, compose/flush, invoice, pay) gets it once.
	resolvedAddr, resolvedPinned, err := resolveTo(context.Background(), to,
		fs.Lookup("maildb").Value.String(), fs.Lookup("daemon").Value.String())
	if err != nil {
		return err
	}
	to = resolvedAddr
	if pinned == "" {
		pinned = resolvedPinned
	}
	if pinned == "" {
		return fmt.Errorf("%s resolved to %s but no pinned sig is known: pass -pinned-sig HEX, or save it once with `spore msg mail add -addr %s -nick NAME -pinned SIG`. The pinned sig is your out-of-band trust anchor — Spore will not guess it", to, to, to)
	}

	plaintext, err := readPlaintext(msgFile)
	if err != nil {
		return err
	}
	if len(plaintext) == 0 {
		return errors.New("send-e2: empty plaintext")
	}
	st, err := e2Store(fs.Lookup("store").Value.String(), fs.Lookup("store-token").Value.String(), fs.Lookup("store-key").Value.String())
	if err != nil {
		return err
	}
	id, err := readHexFile(identity, 32)
	if err != nil {
		return err
	}
	var b *ratchet.SPKBundle
	contact, haveContact := contactForTo(fs.Lookup("maildb").Value.String(), to)
	b, err = pickBundle(context.Background(), bundle, bundleURL, bundleToken, contact, haveContact,
		fetchBundle, func(m string) { fmt.Fprintln(os.Stderr, "send-e2:", m) })
	if err != nil {
		return err
	}
	sig, err := hex.DecodeString(pinned)
	if err != nil {
		return err
	}
	if len(sig) != 32 {
		return errors.New("-pinned-sig must be 32-byte hex")
	}
	stateDir := fs.Lookup("state-dir").Value.String()
	stateKeyFile := fs.Lookup("state-key").Value.String()
	if stateDir == "" || stateKeyFile == "" {
		return errors.New("E2 requires -state-dir and -state-key")
	}
	stateKey, err := readHexFile(stateKeyFile, 32)
	if err != nil {
		return err
	}
	sessionTTL, err := time.ParseDuration(fs.Lookup("session-ttl").Value.String())
	if err != nil {
		return err
	}
	// Apply expiry before restoring any durable session so stale key material
	// cannot process a frame during this invocation.
	states, err := ratchetwire.NewFileStateStore(stateDir, stateKey)
	if err != nil {
		return err
	}
	ep, err := ratchetwire.NewDurableEndpointWithExpiry(st, states, sessionTTL, time.Now())
	if err != nil {
		return err
	}
	_, raw, err := ep.SendFirst(id, b, sig, plaintext, time.Now().Add(ttl))
	if err != nil {
		return err
	}
	c, err := e2Carrier(fs)
	if err != nil {
		return err
	}
	// Pay-with-message: parse -amount, validate the carrier can actually
	// carry value, and attach it to the SAME tx as the pointer. A refusal
	// here is deliberate: better to fail loudly than silently send an
	// unpaid message the sender believes was paid.
	hint := uint64(1) // postage default
	if amount != "" {
		asset, atomic, aerr := parseAmountFlag(amount)
		if aerr != nil {
			return aerr
		}
		if !carrierCarriesValue(fs.Lookup("chain").Value.String()) {
			return fmt.Errorf("-amount %s%s is not supported on the %s carrier (value-carrying: dero|evm); refusing to send an unpaid message as if paid", formatAmount(asset, atomic), asset, fs.Lookup("chain").Value.String())
		}
		if atomic < hint {
			return fmt.Errorf("-amount rounds to %d atomic units, below the 1-unit postage floor", atomic)
		}
		hint = atomic
	}
	r, err := c.PostPointer(context.Background(), to, raw, hint)
	if err != nil {
		return err
	}
	fmt.Printf("sent-e2 txid %s pointer %x", r.TxID, raw)
	if amount != "" {
		if asset, atomic, aerr := parseAmountFlag(amount); aerr == nil {
			fmt.Printf(" PAID %s %s", formatAmount(asset, atomic), strings.ToUpper(asset))
		}
	}
	fmt.Println()
	return nil
}

// msgForwardE2 re-sends an existing decrypted message (e.g. one saved by
// recv-e2 -out-dir) to a NEW recipient. It starts a fresh X3DH session with
// that recipient — forward is a new conversation, not a continuation — and
// reuses the exact sendE2Core path send-e2 uses, so bundle discovery,
// pinning, durable state, and the pointer post all behave identically.
func msgForwardE2(args []string) {
	fs := flag.NewFlagSet("msg forward-e2", flag.ExitOnError)
	to := fs.String("to", "", "new recipient chain address")
	identity := fs.String("identity", "", "file containing sender identity private key hex")
	bundle := fs.String("bundle", "", "recipient SPK bundle JSON file (mutually exclusive with -bundle-url)")
	bundleURL := fs.String("bundle-url", "", "fetch recipient SPK bundle from a mailbox GET /prekey URL (mutually exclusive with -bundle)")
	bundleToken := fs.String("bundle-token", "", "bearer token for -bundle-url, if the mailbox requires auth")
	pinned := fs.String("pinned-sig", "", "recipient signing public key hex")
	file := fs.String("file", "", "the decrypted message file to forward (e.g. a <txid>.msg from recv-e2 -out-dir)")
	amount := fs.String("amount", "", "optional pay-with-message value, e.g. 5.5dero")
	ttl := fs.Duration("ttl", 24*time.Hour, "frame retention")
	e2Common(fs)
	_ = fs.Parse(args)
	if err := loadConfigForFlags(fs); err != nil {
		check(err)
	}
	// -pinned-sig may be omitted: a maildb contact nickname supplies it via
	// resolveTo inside sendE2Core.
	if *to == "" || *identity == "" || *file == "" {
		check(errors.New("forward-e2 requires -to (address, contact nickname, or DeroNS name), -identity, -file, and exactly one of -bundle or -bundle-url"))
	}
	if (*bundle == "") == (*bundleURL == "") {
		check(errors.New("forward-e2 requires exactly one of -bundle or -bundle-url"))
	}
	if err := sendE2Core(fs, *to, *identity, *bundle, *bundleURL, *bundleToken, *pinned, *file, *amount, *ttl); err != nil {
		check(err)
	}
}

func msgRecvE2(args []string) {
	fs := flag.NewFlagSet("msg recv-e2", flag.ExitOnError)
	identity := fs.String("identity", "", "our identity private key file")
	spk := fs.String("spk", "", "our signed-prekey private key file")
	opk := fs.String("opk", "", "legacy single one-time-prekey private key file")
	opkPool := fs.String("opk-pool", "", "endpoint-local persistent one-time-prekey pool JSON (preferred)")
	interval := fs.Duration("interval", 3*time.Second, "poll interval")
	min := fs.Uint64("min-height", 0, "scan height")
	autoAck := fs.Bool("auto-ack", false, "reply 'delivered' on the same session after each successfully decrypted message (delivery receipts)")
	ackTTL := fs.Duration("ack-ttl", 24*time.Hour, "frame retention for auto-ack receipts")
	outDir := fs.String("out-dir", "", "write each received message body to a file in this dir (named <txid>.msg) instead of stdout — attachments/keep-a-copy mode")
	ntfy := fs.String("ntfy", "", "POST a metadata-only notification to an ntfy/webhook URL on each message (plaintext never leaves the client)")
	notifyEmail := fs.String("notify-email", "", "send a metadata-only email notification to this address (SMTP settings come from environment)")
	notifySMS := fs.String("notify-sms", "", "send a metadata-only SMS notification to this E.164 number (Twilio settings come from environment)")
	notifySMTPHost := fs.String("notify-smtp-host", "", "SMTP host for metadata-only email notifications")
	notifySMTPPort := fs.Int("notify-smtp-port", 587, "SMTP port for metadata-only email notifications")
	notifySMTPFrom := fs.String("notify-smtp-from", "", "SMTP From address for metadata-only email notifications")
	notifySMTPUser := fs.String("notify-smtp-user", "", "SMTP username (password from SPORE_NOTIFY_SMTP_PASSWORD)")
	notifyTwilioSID := fs.String("notify-twilio-sid", "", "Twilio account SID (auth token from SPORE_NOTIFY_TWILIO_AUTH_TOKEN)")
	notifyTwilioFrom := fs.String("notify-twilio-from", "", "Twilio sender number")
	// -maildb is registered by e2Common (shared with send paths for name
	// resolution); read it after Parse rather than redeclaring it — a
	// duplicate fs.String panics with "flag redefined".
	e2Common(fs)
	_ = fs.Parse(args)
	if err := loadConfigForFlags(fs); err != nil {
		check(err)
	}
	// Validate and create the attachment output directory before starting the
	// chain watcher. Receiving FrameInit consumes a one-time prekey and writes
	// ratchet state; a bad output path must not consume crypto state and then
	// force the operator to replay a frame that can no longer be opened.
	if *outDir != "" {
		if err := os.MkdirAll(*outDir, 0700); err != nil {
			check(fmt.Errorf("recv-e2: create -out-dir: %w", err))
		}
	}
	maildbPath := fs.Lookup("maildb").Value.String()
	webhookURL := *ntfy
	webhookToken := ""
	if webhookURL != "" {
		// The old -ntfy form is retained as a webhook-compatible alias. Its
		// optional bearer secret comes only from the environment.
		webhookToken = os.Getenv("SPORE_NOTIFY_WEBHOOK_TOKEN")
	}
	dispatcher, err := notify.NewFromEnv(notify.Options{
		WebhookURL: webhookURL, WebhookToken: webhookToken,
		EmailTo: *notifyEmail, SMSTo: *notifySMS,
		SMTPHost: *notifySMTPHost, SMTPPort: *notifySMTPPort,
		SMTPFrom: *notifySMTPFrom, SMTPUsername: *notifySMTPUser,
		TwilioSID: *notifyTwilioSID, TwilioFrom: *notifyTwilioFrom,
	})
	check(err)
	if *identity == "" || *spk == "" {
		check(errors.New("recv-e2 requires -identity and -spk"))
	}
	st, err := e2Store(fs.Lookup("store").Value.String(), fs.Lookup("store-token").Value.String(), fs.Lookup("store-key").Value.String())
	check(err)
	ik, err := readHexFile(*identity, 32)
	check(err)
	sk, err := readHexFile(*spk, 32)
	check(err)
	var op *[32]byte
	var pool *ratchetwire.OPKPool
	if *opkPool != "" {
		pool, err = ratchetwire.NewPersistentOPKPool(*opkPool)
		check(err)
	}
	if *opk != "" {
		x, e := readHexFile(*opk, 32)
		check(e)
		op = &[32]byte{}
		copy(op[:], x)
	}
	c, err := e2Carrier(fs)
	check(err)
	stateDir := fs.Lookup("state-dir").Value.String()
	stateKeyFile := fs.Lookup("state-key").Value.String()
	if stateDir == "" || stateKeyFile == "" {
		check(errors.New("E2 requires -state-dir and -state-key"))
	}
	stateKey, err := readHexFile(stateKeyFile, 32)
	check(err)
	sessionTTL, err := time.ParseDuration(fs.Lookup("session-ttl").Value.String())
	check(err)
	states, err := ratchetwire.NewFileStateStore(stateDir, stateKey)
	check(err)
	ep, err := ratchetwire.NewDurableEndpointWithExpiry(st, states, sessionTTL, time.Now())
	check(err)
	// Open the mail store ONCE, not per message (re-reading the whole JSON
	// file for every delivery is wasteful, and a per-message Open failure
	// would be silently swallowed). Fail loudly up front instead.
	var mdb *maildb.MailDB
	if maildbPath != "" {
		mdb, err = maildb.Open(maildbPath)
		check(err)
	}
	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer cancel()

	// Retry queue. "The body is not retrievable yet" is a NORMAL state on a
	// chain — the sender may push it moments after the pointer lands, or the
	// mailbox may be briefly down — so a fetch failure is remembered and
	// re-attempted instead of throwing the pointer away.
	//
	// This cannot recover a message whose POINTER never arrived: no CID was
	// ever learned, so nothing local can find the body. That case is the loss
	// ledger below, not this queue.
	retryQ := ratchetwire.NewRetryQueue(ratchetwire.DefaultRetryQueueCap)

	// Loss reporting. A message whose ciphertext never arrives is only
	// provably lost once its buffered key is swept past the burn deadline
	// (forward secrecy deletes it), so Expire performs that sweep and the
	// resulting picture is reported whenever it changes. This keeps a
	// conversation with holes from being silently presented as complete.
	gapTick := time.NewTicker(*interval)
	defer gapTick.Stop()
	lastGapNote := ""
	reportGaps := func() {
		ep.Expire(time.Now())
		r := ep.Gaps()
		if r.Empty() {
			if lastGapNote != "" {
				lastGapNote = ""
				fmt.Fprintln(os.Stderr, "e2 gaps: none — every message accounted for")
			}
			return
		}
		note := fmt.Sprintf("%d/%d", len(r.Pending), r.LostTotal)
		if note == lastGapNote {
			return
		}
		lastGapNote = note
		for _, line := range gapReportLines(r) {
			fmt.Fprintln(os.Stderr, line)
		}
	}

	// handleFrame processes one successfully fetched frame. The live path and
	// the retry path both call it, so decryption happens in exactly ONE place
	// — two decrypt paths would be a security surface, not just duplication.
	handleFrame := func(inc chain.Incoming, frame ratchetwire.Frame, p ratchetwire.Pointer) {
		var plain []byte
		var decErr error
		switch frame.Kind {
		case ratchetwire.FrameInit:
			body, bodyErr := ratchetwire.GetBody(st, p, time.Now())
			if bodyErr != nil {
				fmt.Fprintln(os.Stderr, "e2 frame:", bodyErr)
				return
			}
			if pool != nil {
				plain, decErr = ep.ReceiveFirstFromOPKPool(ik, sk, pool, frame, body)
			} else {
				plain, decErr = ep.ReceiveFirst(ik, sk, op, frame, body)
			}
		case ratchetwire.FrameMessage:
			// Continuations must use the installed ratchet session. Never
			// reinterpret them as a fresh handshake (downgrade resistance).
			plain, decErr = ep.ReceiveNext(p, time.Now())
		default:
			decErr = ratchetwire.ErrLegacyDowngrade
		}
		if decErr != nil {
			fmt.Fprintln(os.Stderr, "e2 decrypt:", decErr)
			return
		}
		// Receipts are ratcheted messages like any other: detect the
		// envelope and surface it as an ack line instead of a message.
		receiptInReplyTo, receiptStatus, isReceipt := parseReceipt(plain)
		if isReceipt {
			fmt.Printf("ack %s: %s (for %s)\n", shortTx(inc.TxID), receiptStatus, shortTx(receiptInReplyTo))
			return
		}
		// Money envelopes (invoice/payment) ride the session like
		// receipts: surface them as money lines, not message bodies.
		if kind, summary, isMoney := parseMoneyEnvelope(plain); isMoney {
			_ = kind
			fmt.Printf("%s %s\n", shortTx(inc.TxID), summary)
			return
		}
		// Attachments / keep-a-copy mode: write the decrypted body to a
		// file named by txid instead of printing it.
		if *outDir != "" {
			if err := os.WriteFile(filepath.Join(*outDir, shortTx(inc.TxID)+".msg"), plain, 0600); err != nil {
				fmt.Fprintln(os.Stderr, "e2 out-dir:", err)
				return
			}
			fmt.Printf("msg %s: saved %s/%s.msg\n", shortTx(inc.TxID), *outDir, shortTx(inc.TxID))
		} else {
			fmt.Printf("msg %s: %s\n", shortTx(inc.TxID), plain)
		}
		// Pay-with-message: surface any native value that rode the
		// pointer tx. Postage (1 atomic) is noise; anything above it
		// is money and gets its own line.
		if inc.Amount > 1 {
			fmt.Printf("  ↳ received %d atomic units on tx %s\n", inc.Amount, shortTx(inc.TxID))
		}
		// Mail-store hook: record into threads + search index. Blocked
		// senders were already dropped before decryption, so everything
		// recorded here passed the allowlist.
		if mdb != nil {
			if rerr := mdb.RecordMessage(hex.EncodeToString(frame.SessionID[:]), inc.Sender, inc.TxID, time.Now(), plain); rerr != nil {
				fmt.Fprintln(os.Stderr, "e2 maildb:", rerr)
			}
		}
		// Notify only after local decryption and never include plaintext.
		// Provider failures are diagnostics; they must not stop receiving.
		if *ntfy != "" || *notifyEmail != "" || *notifySMS != "" {
			if nerr := dispatcher.Send(notify.Event{TxID: inc.TxID, Subject: "Spore private message", Received: time.Now()}); nerr != nil {
				fmt.Fprintln(os.Stderr, "e2 notify:", nerr)
			}
		}
		if *autoAck && frame.SessionID != ([8]byte{}) {
			// Reply "delivered" on the same session; the sender's recv
			// side prints it as an ack line. Best-effort: a failed ack
			// send or post is logged, never fatal.
			_, raw, ackErr := sendReceipt(ep, frame.SessionID, inc.TxID, "delivered", *ackTTL)
			if ackErr != nil {
				fmt.Fprintln(os.Stderr, "e2 ack:", ackErr)
				return
			}
			if _, postErr := c.PostPointer(ctx, inc.Sender, raw, 1); postErr != nil {
				fmt.Fprintln(os.Stderr, "e2 ack post:", postErr)
			}
		}
	}

	// retryDue re-attempts bodies whose fetch failed earlier. Entries past
	// their burn deadline are abandoned rather than retried forever: the store
	// may have reaped the body and the ratchet key may be swept, so they are
	// confirmed losses.
	retryDue := func() {
		now := time.Now()
		for _, pf := range retryQ.Expired(now) {
			fmt.Fprintf(os.Stderr, "e2 retry: gave up on %s (deadline passed — message lost)\n", shortTx(pf.TxID))
		}
		for _, pf := range retryQ.Due(now) {
			payload, encErr := c.Codec.EncodePointer(ratchetwire.PointerPayload{
				Version:      ratchetwire.PointerV1,
				Route:        pf.Pointer.Route,
				CID:          pf.Pointer.CID,
				BurnDeadline: pf.Pointer.BurnDeadline,
			})
			if encErr != nil {
				retryQ.Resolve(pf.Pointer.CID)
				continue
			}
			inc := chain.Incoming{TxID: pf.TxID, Sender: pf.Sender, Payload: payload}
			frame, p, ferr := c.FetchIncomingE2(st, inc, now)
			if ferr != nil {
				retryQ.Record(pf.Pointer.CID, now, ferr)
				continue
			}
			retryQ.Resolve(pf.Pointer.CID)
			handleFrame(inc, frame, p)
			reportGaps()
		}
	}

	in, errs := ratchetwire.WatchE2(ctx, c, chain.WatchOpts{MinHeight: *min, Interval: *interval})
	for {
		select {
		case inc, ok := <-in:
			if !ok {
				return
			}
			// Allowlist check BEFORE any decryption: a blocked sender's
			// frame never touches ratchet state and is never even parsed
			// past the pointer. Chain senders are pseudonymous, so this
			// filters by chain identity (what maildb knows), not by
			// long-term key.
			if mdb != nil && !mdb.Allowed(inc.Sender) {
				fmt.Fprintf(os.Stderr, "e2: dropped message from blocked sender %s\n", shortTx(inc.Sender))
				continue
			}
			frame, p, e := c.FetchIncomingE2(st, inc, time.Now())
			if e != nil {
				// The pointer is known even when the body is not, so queue a
				// retry rather than losing the message to a transient miss.
				if p.CID == ([32]byte{}) {
					fmt.Fprintln(os.Stderr, "e2 frame:", e)
					continue
				}
				if !retryQ.NoteFetchFailure(p, inc.Sender, inc.TxID, time.Now(), e) {
					fmt.Fprintf(os.Stderr, "e2 retry: queue full (%d), abandoning %s\n", retryQ.Cap(), shortTx(inc.TxID))
				}
				continue
			}
			handleFrame(inc, frame, p)
			reportGaps()
		case <-gapTick.C:
			retryDue()
			reportGaps()
		case e := <-errs:
			if e != nil {
				fmt.Fprintln(os.Stderr, "e2 watch:", e)
			}
		case <-ctx.Done():
			return
		}
	}
}

// msgReplyE2 continues an existing ratchet session: the email "reply" —
// same conversation, SendNext on the durable session. The pointer is posted
// to the recipient chain address like any other continuation.
func msgReplyE2(args []string) {
	fs := flag.NewFlagSet("msg reply-e2", flag.ExitOnError)
	to := fs.String("to", "", "recipient chain address")
	sessionHex := fs.String("session", "", "16-hex session id (see msg sessions)")
	msgFile := fs.String("msg-file", "", "file containing plaintext (use '-' or omit for stdin; never pass plaintext as an argv flag)")
	ttl := fs.Duration("ttl", 24*time.Hour, "frame retention")
	e2Common(fs)
	_ = fs.Parse(args)
	if err := loadConfigForFlags(fs); err != nil {
		check(err)
	}
	if *to == "" || *sessionHex == "" {
		check(errors.New("reply-e2 requires -to and -session (plaintext via -msg-file or stdin)"))
	}
	rawID, err := hex.DecodeString(*sessionHex)
	check(err)
	if len(rawID) != 8 {
		check(errors.New("-session must be 16 hex chars (8 bytes)"))
	}
	var sessionID [8]byte
	copy(sessionID[:], rawID)
	plaintext, err := readPlaintext(*msgFile)
	check(err)
	if len(plaintext) == 0 {
		check(errors.New("reply-e2: empty plaintext"))
	}
	st, err := e2Store(fs.Lookup("store").Value.String(), fs.Lookup("store-token").Value.String(), fs.Lookup("store-key").Value.String())
	check(err)
	stateDir := fs.Lookup("state-dir").Value.String()
	stateKeyFile := fs.Lookup("state-key").Value.String()
	if stateDir == "" || stateKeyFile == "" {
		check(errors.New("E2 requires -state-dir and -state-key"))
	}
	stateKey, err := readHexFile(stateKeyFile, 32)
	check(err)
	sessionTTL, err := time.ParseDuration(fs.Lookup("session-ttl").Value.String())
	check(err)
	states, err := ratchetwire.NewFileStateStore(stateDir, stateKey)
	check(err)
	ep, err := ratchetwire.NewDurableEndpointWithExpiry(st, states, sessionTTL, time.Now())
	check(err)
	_, raw, err := ep.SendNext(sessionID, plaintext, time.Now().Add(*ttl))
	check(err)
	c, err := e2Carrier(fs)
	check(err)
	r, err := c.PostPointer(context.Background(), *to, raw, 1)
	check(err)
	fmt.Printf("reply-e2 txid %s pointer %x\n", r.TxID, raw)
}

// msgSessions lists the durable ratchet sessions for the configured state
// dir. Sessions are the threads: each id is one conversation you can reply
// into with reply-e2.
func msgSessions(args []string) {
	fs := flag.NewFlagSet("msg sessions", flag.ExitOnError)
	e2Common(fs)
	_ = fs.Parse(args)
	if err := loadConfigForFlags(fs); err != nil {
		check(err)
	}
	// Listing sessions never touches the off-chain body store, so -store is
	// optional here: fall back to an in-memory store when omitted.
	var st ratchetwire.BodyStore
	if storeURL := fs.Lookup("store").Value.String(); storeURL != "" {
		s, err := e2Store(storeURL, fs.Lookup("store-token").Value.String(), fs.Lookup("store-key").Value.String())
		check(err)
		st = s
	} else {
		st = store.NewMemStore()
	}
	stateDir := fs.Lookup("state-dir").Value.String()
	stateKeyFile := fs.Lookup("state-key").Value.String()
	if stateDir == "" || stateKeyFile == "" {
		check(errors.New("E2 requires -state-dir and -state-key"))
	}
	stateKey, err := readHexFile(stateKeyFile, 32)
	check(err)
	sessionTTL, err := time.ParseDuration(fs.Lookup("session-ttl").Value.String())
	check(err)
	states, err := ratchetwire.NewFileStateStore(stateDir, stateKey)
	check(err)
	ep, err := ratchetwire.NewDurableEndpointWithExpiry(st, states, sessionTTL, time.Now())
	check(err)
	ids := ep.Sessions.IDs()
	if len(ids) == 0 {
		fmt.Println("no sessions")
		return
	}
	for _, id := range ids {
		fmt.Printf("%x\n", id)
	}
}
