#!/bin/bash -eu
# Copyright (c) 2026 the spore authors
#
# Build the SPR2 wire parser fuzz targets as libFuzzer binaries via
# compile_native_go_fuzzer (go-118-fuzz-build, v1 import-rewrite flow) —
# the same recipe as the oss-fuzz fork's projects/spore/build.sh, relocated
# here per ClusterFuzzLite's build contract.
#
# Required preamble: go-118-fuzz-build rewrites the harness file's `testing`
# import to its own shim, so github.com/AdamKorcz/go-118-fuzz-build/testing
# must be resolvable from the spore module. We add it with a replace
# directive pointing at the pinned checkout in $SRC/fuzzbuild, so spore's
# own go.mod stays dependency-free for normal users. All modifications to
# the source tree are reverted on exit so the build is side-effect free.

cd $SRC/spore

cleanup() {
  rm -f ./registerfuzzbuild.go
  git checkout -- go.mod go.sum 2>/dev/null || true
}
trap cleanup EXIT

# Dummy import keeps the dependency in the module graph through `go mod tidy`
# (without it, tidy prunes the require/replace lines we appended).
cat > ./registerfuzzbuild.go <<'EOF'
package registerfuzzbuild

import _ "github.com/AdamKorcz/go-118-fuzz-build/testing"
EOF

cat >> go.mod <<'EOF'

require github.com/AdamKorcz/go-118-fuzz-build v0.0.0

replace github.com/AdamKorcz/go-118-fuzz-build => ../fuzzbuild
EOF

go mod tidy

# The seed corpus files are generated by TestGenerateSeedCorpus
# (SPORE_GEN_SEED_CORPUS=1) and committed under
# internal/wirefuzz/testdata/fuzz/seedcorpus/. Zip them per target.
mkdir -p $OUT
for target in frameparse handshakeunmarshal messageunmarshal fabricrpc2frame; do
  zip -q -j $OUT/${target}_fuzzer_seed_corpus.zip \
    internal/wirefuzz/testdata/fuzz/seedcorpus/*
done

# Uses the v1 flow (compile_native_go_fuzzer -> go-118-fuzz-build), which
# rewrites the harness file's `testing` import to the shim package. The v2
# tool instead overlays GOROOT/src/testing/testing.go with hooks and is
# sensitive to the exact Go stdlib layout; v1 is stable across Go releases.
compile_native_go_fuzzer github.com/liqdmetal/spore/internal/wirefuzz FuzzFrameParse frameparse_fuzzer
compile_native_go_fuzzer github.com/liqdmetal/spore/internal/wirefuzz FuzzHandshakeUnmarshal handshakeunmarshal_fuzzer
compile_native_go_fuzzer github.com/liqdmetal/spore/internal/wirefuzz FuzzMessageUnmarshal messageunmarshal_fuzzer
# The fabric's second encoding (CBOR/rpc2, F4a): DecodeRPC2Frame is the
# relay-facing hostile-frame parse surface for Peer.FabricReg/Put/Pop.
compile_native_go_fuzzer github.com/liqdmetal/spore/internal/wirefuzz FuzzFabricRPC2Frame fabricrpc2frame_fuzzer
