#!/bin/bash -eu
# Copyright (c) 2026 the spore authors
#
# Build the SPR2 wire parser fuzz targets as libFuzzer binaries via
# compile_native_go_fuzzer (go-118-fuzz-build, v1 import-rewrite flow) —
# the same recipe as the oss-fuzz fork's projects/spore/build.sh, relocated
# here per ClusterFuzzLite's build contract.
#
# Required preamble: go-118-fuzz-build rewrites the harness file's `testing`
# import to its own shim, so github.com/AdamKorcz/go-118-fuzz-build/testing
# must be resolvable from the spore module. We add it with a replace
# directive pointing at the pinned checkout in $SRC/fuzzbuild, so spore's
# own go.mod stays dependency-free for normal users. All modifications to
# the source tree are reverted on exit so the build is side-effect free.

# record_coverage_function_name F <func>
#
# base-runner's coverage script maps binary -> fuzz-function via
# $OUT/fuzzer_function_names.json to build its -test.run flag; the v1 flow
# never writes that file (only the v2 flow does), so the mapping is
# recorded here alongside each coverage binary.
record_coverage_function_name() {
  if [ "${SANITIZER:-}" = coverage ]; then
    [ -s "${OUT}/fuzzer_function_names.json" ] || echo '{}' > "${OUT}/fuzzer_function_names.json"
    jq --arg k "$1" --arg v "$2" '.[$k] = $v' "${OUT}/fuzzer_function_names.json" \
      > "${OUT}/fuzzer_function_names.json.tmp" \
      && mv "${OUT}/fuzzer_function_names.json.tmp" "${OUT}/fuzzer_function_names.json"
  fi
}

cd $SRC/spore

cleanup() {
  rm -f ./registerfuzzbuild.go
  git checkout -- go.mod go.sum 2>/dev/null || true
}
trap cleanup EXIT

# Dummy import keeps the dependency in the module graph through `go mod tidy`
# (without it, tidy prunes the require/replace lines we appended).
cat > ./registerfuzzbuild.go <<'EOF'
package registerfuzzbuild

import _ "github.com/AdamKorcz/go-118-fuzz-build/testing"
EOF

cat >> go.mod <<'EOF'

require github.com/AdamKorcz/go-118-fuzz-build v0.0.0

replace github.com/AdamKorcz/go-118-fuzz-build => ../fuzzbuild
EOF

go mod tidy

# The seed corpus files are generated by TestGenerateSeedCorpus
# (SPORE_GEN_SEED_CORPUS=1) and committed under
# internal/wirefuzz/testdata/fuzz/seedcorpus/. Zip them per target.
mkdir -p $OUT
for target in frameparse handshakeunmarshal messageunmarshal fabricrpc2frame; do
  zip -q -j $OUT/${target}_fuzzer_seed_corpus.zip \
    internal/wirefuzz/testdata/fuzz/seedcorpus/*
done

if [ "${SANITIZER:-}" = coverage ]; then
  # The stock v1 coverage build CANNOT work for this repo, structurally:
  # wirefuzz is a test-only package (the harness lives in wirefuzz_test.go),
  # and `go test -cover` instruments only a package's non-test files — so
  # build_native_go_fuzzer_legacy's `go test -c -cover` yields binaries
  # whose profile is empty by construction ("coverage: [no statements]",
  # an all-zeros report — observed live on 2026-09-20). Build the coverage
  # binaries here instead, with -coverpkg over every spore-module package
  # the harness imports, and emit the companion files base-runner's
  # coverage script consumes: fuzzer_function_names.json (v1 never writes
  # it; only the v2 flow does) and the per-target .gocovpath path-
  # translation file, byte-compatible with the legacy build's format.
  # (Known limitation: the script's non-std-lib Go path exercises the
  # harness's inline seeds, not the downloaded corpus — corpus-driven Go
  # coverage would need the v2 flow's parameters machinery.)
  coverpkgs=$(go list -tags gofuzz -deps -test ./internal/wirefuzz \
    | grep -E '^github.com/liqdmetal/spore/[a-z/]+$' | paste -sd, -)
  fuzzed_repo=$(go list -tags gofuzz -f {{.Module}} ./internal/wirefuzz)
  abspath_repo=$(go list -m -tags gofuzz -f {{.Dir}} "$fuzzed_repo" 2>/dev/null \
    || go list -tags gofuzz -f {{.Dir}} "$fuzzed_repo")
  harness_file=$(grep -rl --include='*.go' 'func FuzzFrameParse' ./internal/wirefuzz)
  mkdir -p "$OUT/rawfuzzers"
  for pair in \
    'frameparse_fuzzer FuzzFrameParse' \
    'handshakeunmarshal_fuzzer FuzzHandshakeUnmarshal' \
    'messageunmarshal_fuzzer FuzzMessageUnmarshal' \
    'fabricrpc2frame_fuzzer FuzzFabricRPC2Frame'; do
    set -- $pair
    go test -tags gofuzz -c -coverpkg="$coverpkgs" -o "$OUT/$1" ./internal/wirefuzz
    cp "$harness_file" "$OUT/rawfuzzers/$1"
    echo "s=${fuzzed_repo}=${abspath_repo}=" > "$OUT/$1.gocovpath"
    record_coverage_function_name "$1" "$2"
  done
else
  # Uses the v1 flow (compile_native_go_fuzzer -> go-118-fuzz-build), which
  # rewrites the harness file's `testing` import to the shim package. The v2
  # tool instead overlays GOROOT/src/testing/testing.go with hooks and is
  # sensitive to the exact Go stdlib layout; v1 is stable across Go releases.
  compile_native_go_fuzzer github.com/liqdmetal/spore/internal/wirefuzz FuzzFrameParse frameparse_fuzzer
  compile_native_go_fuzzer github.com/liqdmetal/spore/internal/wirefuzz FuzzHandshakeUnmarshal handshakeunmarshal_fuzzer
  compile_native_go_fuzzer github.com/liqdmetal/spore/internal/wirefuzz FuzzMessageUnmarshal messageunmarshal_fuzzer
  # The fabric's second encoding (CBOR/rpc2, F4a): DecodeRPC2Frame is the
  # relay-facing hostile-frame parse surface for Peer.FabricReg/Put/Pop.
  compile_native_go_fuzzer github.com/liqdmetal/spore/internal/wirefuzz FuzzFabricRPC2Frame fabricrpc2frame_fuzzer
fi
