package fabric

// F1 conformance: docs/interop-vectors.json "fabric_v1" is the golden file
// generated by internal/secure's TestGenerateWireSpecVectors (vectors-first
// rule). This test CONSUMES the committed file the way an independent
// implementation would; the Rust fabric module consumes the same section,
// so the two implementations cannot drift. Negative vectors are rejected-
// by-construction values: an implementation that derives a different-epoch
// handle, omits the nonce from the reg HMAC, accepts a wrong-version
// envelope, or takes a wrong-length pointer must fail here.

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"strconv"
	"testing"
)

type fabricVectors struct {
	FabricV1 struct {
		Seed                 string `json:"seed_hex"`
		Epoch                string `json:"epoch"`
		SID                  string `json:"sid_hex"`
		RegNonce             string `json:"reg_server_nonce"`
		Handle               string `json:"handle_hex"`
		HandleNegEpoch8      string `json:"handle_negative_epoch8_hex"`
		RegToken             string `json:"reg_token_hex"`
		RegTokenNegNonce     string `json:"reg_token_negative_other_nonce_hex"`
		PointerRoute         string `json:"pointer_route_hex"`
		PointerDeadline      string `json:"pointer_deadline"`
		Pointer              string `json:"pointer_hex"`
		EnvelopeReceived     string `json:"envelope_received_at"`
		Envelope             string `json:"envelope_hex"`
		EnvelopeBadVer       string `json:"envelope_negative_bad_version_hex"`
		PointerNegLen73Input string `json:"pointer_negative_len73_hex"`
	} `json:"fabric_v1"`
}

func loadFabricVectors(t *testing.T) fabricVectors {
	t.Helper()
	raw, err := os.ReadFile("../../docs/interop-vectors.json")
	if err != nil {
		t.Fatalf("vectors file missing (run TestGenerateWireSpecVectors): %v", err)
	}
	var v fabricVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse interop-vectors.json: %v", err)
	}
	if v.FabricV1.Handle == "" || v.FabricV1.Envelope == "" {
		t.Fatal("vectors file missing fabric_v1 section")
	}
	return v
}

func TestFabricHandleVector(t *testing.T) {
	fv := loadFabricVectors(t).FabricV1

	seedB, _ := hex.DecodeString(fv.Seed)
	sidB, _ := hex.DecodeString(fv.SID)
	var seed [32]byte
	var sid [8]byte
	copy(seed[:], seedB)
	copy(sid[:], sidB)

	epoch64, err := strconv.ParseUint(fv.Epoch, 10, 32)
	if err != nil {
		t.Fatalf("parse epoch: %v", err)
	}
	epoch := uint32(epoch64)

	h, err := FabricHandle(seed, epoch, sid)
	if err != nil {
		t.Fatal(err)
	}
	if got := hex.EncodeToString(h[:]); got != fv.Handle {
		t.Fatalf("handle mismatch:\n got %s\nwant %s", got, fv.Handle)
	}

	// Negative: a different epoch MUST derive a different handle — the whole
	// point of epochs. The vector pins the wrong-epoch value so any change to
	// the derivation (label, salt, info order) fails here too.
	h8, err := FabricHandle(seed, epoch+1, sid)
	if err != nil {
		t.Fatal(err)
	}
	if got := hex.EncodeToString(h8[:]); got != fv.HandleNegEpoch8 {
		t.Fatalf("epoch+1 handle mismatch:\n got %s\nwant %s", got, fv.HandleNegEpoch8)
	}
	if h == h8 {
		t.Fatal("different epochs derived identical handles")
	}
}

func TestFabricRegTokenVector(t *testing.T) {
	fv := loadFabricVectors(t).FabricV1

	seedB, _ := hex.DecodeString(fv.Seed)
	handleB, _ := hex.DecodeString(fv.Handle)
	var seed [32]byte
	var handle [32]byte
	copy(seed[:], seedB)
	copy(handle[:], handleB)

	if got := RegToken(seed, handle, fv.RegNonce); got != fv.RegToken {
		t.Fatalf("reg token mismatch:\n got %s\nwant %s", got, fv.RegToken)
	}
	// Negative: any change to the server nonce must change the token; the
	// pinned wrong-nonce value catches an HMAC that drops the nonce.
	if got := RegToken(seed, handle, fv.RegNonce+"-x"); got != fv.RegTokenNegNonce {
		t.Fatalf("other-nonce token mismatch:\n got %s\nwant %s", got, fv.RegTokenNegNonce)
	}
	if RegToken(seed, handle, fv.RegNonce) == RegToken(seed, handle, fv.RegNonce+"-x") {
		t.Fatal("different nonces produced identical tokens")
	}
}

func TestFabricEnvelopeVector(t *testing.T) {
	fv := loadFabricVectors(t).FabricV1

	envBytes, err := hex.DecodeString(fv.Envelope)
	if err != nil {
		t.Fatal(err)
	}
	env, err := ParseEnvelope(envBytes)
	if err != nil {
		t.Fatalf("parse envelope vector: %v", err)
	}
	if got := hex.EncodeToString(env.Handle[:]); got != fv.Handle {
		t.Fatalf("envelope handle mismatch: got %s want %s", got, fv.Handle)
	}
	if got := hex.EncodeToString(env.Pointer[:]); got != fv.Pointer {
		t.Fatalf("envelope pointer mismatch: got %s want %s", got, fv.Pointer)
	}
	if got := strconv.FormatUint(env.ReceivedAt, 10); got != fv.EnvelopeReceived {
		t.Fatalf("received_at mismatch: got %s want %s", got, fv.EnvelopeReceived)
	}
	// Round-trip: marshal(parse(x)) == x.
	if got := hex.EncodeToString(env.MarshalBinary()); got != fv.Envelope {
		t.Fatalf("envelope round-trip mismatch:\n got %s\nwant %s", got, fv.Envelope)
	}

	// The two planes touch at exactly the seam the design describes: the
	// embedded pointer's Route is the §2-frozen RouteKey of the vector sid.
	routeB, _ := hex.DecodeString(fv.PointerRoute)
	if env.Pointer[0] != 1 || env.Pointer[1] != 0 {
		t.Fatal("embedded pointer header wrong")
	}
	var wantRoute, gotRoute [32]byte
	copy(wantRoute[:], routeB)
	copy(gotRoute[:], env.Pointer[2:34])
	if wantRoute != gotRoute {
		t.Fatal("embedded pointer Route does not match pointer_route_hex vector")
	}
}

func TestFabricNegativeVectorsRefused(t *testing.T) {
	fv := loadFabricVectors(t).FabricV1

	badVer, err := hex.DecodeString(fv.EnvelopeBadVer)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := ParseEnvelope(badVer); err == nil {
		t.Fatal("wrong-version envelope accepted")
	}

	// The 73-byte "pointer" is not an envelope either — length checks are
	// the outermost validation at both the envelope and fput boundaries.
	short, err := hex.DecodeString(fv.PointerNegLen73Input)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := ParseEnvelope(short[:73]); err == nil {
		t.Fatal("73-byte input accepted as envelope")
	}
}
