package fabric

// F4a conformance: docs/interop-vectors.json fabric_v1.rpc2_* pins the
// byte-exact CBOR/rpc2 frames for the Peer.FabricReg/Put/Pop family. The
// vectors are generated by internal/secure (same file as every other fabric
// vector) and consumed byte-for-byte by the Rust relay's conformance test —
// neither encoder can drift. Negative cases prove the decoder's hostile-
// frame posture matches the Rust decoder's: reserved/indefinite heads,
// non-text map keys, deep nesting, and truncation are all refused, and a
// zero-consumption decode is malformed by definition.

import (
	"context"
	"encoding/hex"
	"encoding/json"
	"net"
	"os"
	"testing"
	"time"
)

// mustHex decodes a hex vector or fails the test.
func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex vector: %v", err)
	}
	return b
}

// payloadMap type-asserts a decoded rpc2 payload for assertions.
func payloadMap(t *testing.T, v any) map[string]any {
	t.Helper()
	m, ok := v.(map[string]any)
	if !ok {
		t.Fatalf("payload is %T, want map[string]any", v)
	}
	return m
}

type rpc2Vectors struct {
	FabricV1 struct {
		Handle       string `json:"handle_hex"`
		Token        string `json:"reg_token_hex"`
		Pointer      string `json:"pointer_hex"`
		RPC2SeqPut   string `json:"rpc2_seq_put"`
		RPC2SeqPop   string `json:"rpc2_seq_pop"`
		RPC2ReqFreg  string `json:"rpc2_request_freg_frame_hex"`
		RPC2RespFreg string `json:"rpc2_response_freg_frame_hex"`
		RPC2ReqFput  string `json:"rpc2_request_fput_frame_hex"`
		RPC2RespFput string `json:"rpc2_response_fput_frame_hex"`
		RPC2ReqFpop  string `json:"rpc2_request_fpop_frame_hex"`
		RPC2RespFpop string `json:"rpc2_response_fpop_frame_hex"`
		RPC2RespErr  string `json:"rpc2_response_error_frame_hex"`
	} `json:"fabric_v1"`
}

func loadRPC2Vectors(t *testing.T) rpc2Vectors {
	t.Helper()
	raw, err := os.ReadFile("../../docs/interop-vectors.json")
	if err != nil {
		t.Fatalf("vectors file missing: %v", err)
	}
	var v rpc2Vectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse interop-vectors.json: %v", err)
	}
	if v.FabricV1.RPC2ReqFput == "" {
		t.Fatal("vectors file missing fabric_v1.rpc2_* section (regenerate interop-vectors.json)")
	}
	return v
}

func TestRPC2RequestFramesMatchVectors(t *testing.T) {
	fv := loadRPC2Vectors(t).FabricV1

	// fput: Peer.FabricPut, seq 1 — the vector's seq keys pin the mapping.
	regPayload, err := EncodeFabricReg(fv.Handle, fv.Token, "spore-fabric-vectors", 3600)
	if err != nil {
		t.Fatal(err)
	}
	putPayload, err := EncodeFabricPut(fv.Handle, mustHex(t, fv.Pointer), 4102444800)
	if err != nil {
		t.Fatal(err)
	}
	popPayload, err := EncodeFabricPop(fv.Handle, fv.Token, 64)
	if err != nil {
		t.Fatal(err)
	}
	if seq := rpc2Seq("fput"); seq != 1 {
		t.Fatalf("fput seq = %d, vector pins 1", seq)
	}

	// The builders return ready-encoded payloads (canonical key order); the
	// vectors pin those exact bytes.
	for _, tc := range []struct {
		name    string
		verb    string
		payload []byte
		want    string
	}{
		{"freg", "freg", regPayload, fv.RPC2ReqFreg},
		{"fput", "fput", putPayload, fv.RPC2ReqFput},
		{"fpop", "fpop", popPayload, fv.RPC2ReqFpop},
	} {
		frame := hex.EncodeToString(encodeRPC2Frame(rpc2Methods[tc.verb], rpc2Seq(tc.verb), "", tc.payload))
		if frame != tc.want {
			t.Fatalf("%s request frame mismatch:\n got %s\nwant %s", tc.name, frame, tc.want)
		}
	}
}

func TestRPC2ResponseFramesMatchVectors(t *testing.T) {
	fv := loadRPC2Vectors(t).FabricV1

	// Decode the pinned ok responses with THIS package's decoder.
	decode := func(hexFrame, name string) RPC2Message {
		t.Helper()
		raw, err := hex.DecodeString(hexFrame)
		if err != nil {
			t.Fatal(err)
		}
		msg, err := DecodeRPC2Frame(raw[4:]) // strip the LE32 prefix read_frame consumes
		if err != nil {
			t.Fatalf("%s response decode: %v", name, err)
		}
		return msg
	}

	put := decode(fv.RPC2RespFput, "fput")
	if put.Seq != 1 {
		t.Fatalf("fput response seq = %d, want 1", put.Seq)
	}
	if v, _ := payloadMap(t, put.Payload)["queued"].(bool); !v {
		t.Fatalf("fput response queued = %#v, want true", payloadMap(t, put.Payload)["queued"])
	}

	pop := decode(fv.RPC2RespFpop, "fpop")
	if pop.Seq != 2 {
		t.Fatalf("fpop response seq = %d, want 2", pop.Seq)
	}
	arr, _ := payloadMap(t, pop.Payload)["pointers"].([]any)
	if len(arr) != 1 || arr[0] != fv.Pointer {
		t.Fatalf("fpop response pointers = %#v, want [%s]", payloadMap(t, pop.Payload)["pointers"], fv.Pointer)
	}

	reg := decode(fv.RPC2RespFreg, "freg")
	if reg.Seq != 3 {
		t.Fatalf("freg response seq = %d, want 3", reg.Seq)
	}
	if tok, _ := payloadMap(t, reg.Payload)["token"].(string); tok != fv.Token {
		t.Fatalf("freg response token mismatch")
	}

	// The error response decodes with the verbatim refusal in E, no payload.
	errRaw, err := hex.DecodeString(fv.RPC2RespErr)
	if err != nil {
		t.Fatal(err)
	}
	errMsg, err := DecodeRPC2Frame(errRaw[4:])
	if err != nil {
		t.Fatal(err)
	}
	if errMsg.Error != "503 registry full" {
		t.Fatalf("error response E = %q, want %q", errMsg.Error, "503 registry full")
	}
	if errMsg.Payload != nil {
		t.Fatalf("error response carries a payload: %#v", errMsg.Payload)
	}

	// Round-trip: re-encode the decoded payloads and compare to the pins —
	// the encoder is canonical, not just self-consistent.
	reEncoded := func(m RPC2Message, verb string) string {
		p, err := cborValue(rpc2RestoreNumeric(t, m.Payload))
		if err != nil {
			t.Fatal(err)
		}
		return hex.EncodeToString(encodeRPC2Frame("", m.Seq, m.Error, p))
	}
	if got := reEncoded(put, "fput"); got != fv.RPC2RespFput {
		t.Fatalf("fput response re-encode mismatch:\n got %s\nwant %s", got, fv.RPC2RespFput)
	}
}

// rpc2RestoreNumeric rebuilds exact uint64s from the JSON-shaped decode so a
// re-encode reproduces the pinned bytes (deadline/expiry values exceed float64
// precision nowhere in these vectors, but the coercion is explicit).
func rpc2RestoreNumeric(t *testing.T, v any) map[string]any {
	t.Helper()
	m, ok := v.(map[string]any)
	if !ok {
		t.Fatalf("payload is %T, want map[string]any", v)
	}
	out := make(map[string]any, len(m))
	for k, v := range m {
		switch x := v.(type) {
		case float64:
			out[k] = uint64(x)
		default:
			out[k] = x
		}
	}
	return out
}

func TestRPC2DecoderRefusesHostileFrames(t *testing.T) {
	// Reserved info (28..=30) and indefinite length (31) are rejected.
	for _, head := range []byte{0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdf} {
		if _, _, err := decodeCBORItem([]byte{head, 0x00}, 0); err == nil {
			t.Fatalf("head %#x accepted", head)
		}
	}
	// A map with a non-text key is refused (the rpc2 subset is text-keyed).
	badKey := append(cborMap(1), append(cborUint(1), cborText("v")...)...)
	if _, _, err := decodeCBORItem(badKey, 0); err == nil {
		t.Fatal("non-text map key accepted")
	}
	// Nesting past the hostile-frame depth cap is refused.
	deep := cborText("x")
	for i := 0; i < rpc2MaxDepth+2; i++ {
		deep = append(cborArray(1), deep...)
	}
	if _, _, err := decodeCBORItem(deep, 0); err == nil {
		t.Fatal("over-deep nesting accepted")
	}
	// Truncated containers are refused.
	trunc := cborMap(2)
	trunc = append(trunc, cborKV("a", cborText("b"))...)
	if _, _, err := decodeCBORItem(trunc, 0); err == nil {
		t.Fatal("truncated map accepted")
	}
	// A header map that is not a map is refused.
	if _, err := DecodeRPC2Frame(cborText("not a map")); err == nil {
		t.Fatal("non-map header accepted")
	}
	// Unknown simple values (floats, undefined) never appear in fabric
	// payloads and are refused.
	if _, _, err := decodeCBORItem([]byte{0xf9, 0x3c, 0x00}, 0); err == nil {
		t.Fatal("float16 accepted")
	}
	// A near-2^64 declared length must REFUSE, not wrap the truncation
	// check and panic the allocator (found by FuzzFabricRPC2Frame's first
	// seed run; the regression pins the wrap-free comparison — n is
	// compared against the remaining bytes directly, never added).
	huge := []byte{0x5b, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x00}
	if _, _, err := decodeCBORItem(huge, 0); err == nil {
		t.Fatal("huge declared byte length accepted (length check wrapped)")
	}
	hugeText := []byte{0x7b, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff}
	if _, _, err := decodeCBORItem(hugeText, 0); err == nil {
		t.Fatal("huge declared text length accepted (length check wrapped)")
	}
	// The UTF-8 gate: text items carrying invalid UTF-8 are malformed,
	// byte-for-byte parity with the Rust decoder's from_utf8.
	if _, _, err := decodeCBORItem([]byte{0x63, 0xff, 0xfe, 0xfd}, 0); err == nil {
		t.Fatal("invalid UTF-8 text accepted (Rust decoder refuses it)")
	}
}

func TestRPC2TransportVectorRoundTripOnSocket(t *testing.T) {
	// The CBORTransport against a real listener that serves the pinned
	// response: the full client-visible path (encode request → wire →
	// decode response → JSON-shaped payload) agrees with the golden bytes.
	fv := loadRPC2Vectors(t).FabricV1
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Skipf("no local listener: %v", err)
	}
	defer ln.Close()
	go func() {
		conn, err := ln.Accept()
		if err != nil {
			return
		}
		defer conn.Close()
		req, rerr := readFrame(conn)
		if rerr != nil {
			return
		}
		// The request must decode to the pinned semantic payload.
		msg, derr := DecodeRPC2Frame(req)
		if derr != nil || msg.Method != "Peer.FabricPut" {
			return
		}
		resp, _ := hex.DecodeString(fv.RPC2RespFput)
		_, _ = conn.Write(resp)
	}()

	tr := NewCBORTransport(ln.Addr().String())
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	out, err := tr.RoundTrip(ctx, Request{Verb: "fput", Payload: map[string]any{
		"handle": fv.Handle, "pointer_hex": fv.Pointer, "deadline": uint64(4102444800),
	}})
	if err != nil {
		t.Fatal(err)
	}
	if v, _ := out.Payload["queued"].(bool); !v {
		t.Fatalf("queued = %#v, want true", out.Payload["queued"])
	}
}
