name: ReleaseP7
permissions:
  contents: write
  id-token: write
  actions: read
on:
  push:
    tags:
      - "v*"
jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - run: echo "p7 external reusable call at main"
  probe-call:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main
